name: todopomodoro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  provider: ^6.0.5
  google_fonts: ^6.2.1
  uuid: ^4.4.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3
  bcrypt: ^1.1.3
  shared_preferences: ^2.5.3
  restart_app: ^1.2.1
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_storage: ^13.0.1
  firebase_app_check: 0.4.0+1
  cloud_firestore: ^6.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.6

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/pictures/icons/android/app_icon.png"
  image_path_ios: "assets/pictures/icons/ios/app_icon.png"
  adaptive_icon_background: "assets/pictures/icons/app_icon.png"
  adaptive_icon_foreground: "assets/pictures/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/data/data.json
    - assets/data/history.json
    ################ Page - Bilder ################
    - assets/pictures/page/
    ################ Profil - Bilder ################
    - assets/pictures/profile/
    ################ Background - Bilder ################
    - assets/pictures/background/